### PR TITLE
Multiple minor improvements, more unification

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by jackspirou** [comment]
Im not a huge fan of long single line statements (the debug printfs).  I like the idea that you could print the page out on a printer and the code would still look pretty (not that anyone actually does that much anymore).  Its really more personal preference than anything else. 

Anyway, LGTM!

**Comment by tboerger** [comment]
> Im not a huge fan of long single line statements (the debug printfs). I like the idea that you could print the page out on a printer and the code would still look pretty (not that anyone actually does that much anymore). Its really more personal preference than anything else.

That was not my idea, I don't really like it as well. I just did some reformatting to it :)

**Comment by jackspirou** [comment]
@tboerger i was referring to the reformatting in that now it goes off the page vs before.

I will admit I added in the DEBUG printf statements since they proved really useful when using the plugin for more complex integrations.  

I could make the string `"[debug] Webhook %d\n  URL: %s\n  METHOD: %s\n  HEADERS: %s\n  REQUEST BODY: %s\n  RESPONSE STATUS: %s\n  RESPONSE BODY: %s\n"` a constant and move that out of the print statement.  

Can you think of any other cleaner ways to handle the DEBUG prints? Split the vars up into different statements? I agree its not pretty...

**Comment by jackspirou** [comment]
We also can just merge this now and worry about the ugly DEBUG statements later.  Like you said, this PR just reformats and unifies some things :)

**Comment by nlf** [comment]
LGTM

**Comment by jackspirou** [comment]
LGTM

**Pull request merged**
