### PR TITLE
Update to 0.5 plugin format

### PR DESCRIPTION
**Pull request by rdumont**
This PR changes the plugin to be compatible with Drone 0.5.

### CODE REVIEW

**Comment by xxxtonixxx** [comment]
Any news on update this plugin? (Maybe it would be better to update to 0.7)

**Comment by Caballerog** [comment]
@xxxtonixxx would be great update this plugin to 0.7 :-)

**Comment by mrueg** [comment]
@bradrydzewski @tboerger  can you take a look?

**Comment by tboerger** [comment]
This pr doesn't use the default plugin structure, doesn't use govendor for vendoring the deps and is missing lots of environment variable mappings

**Comment by josmo** [comment]
I created a new PR that I think conforms more with the default structure, uses govendor and has all the normal environment variable mappings (I think ;)). If https://github.com/drone-plugins/drone-webhook/pull/18 works I vote we close this one out.

**Comment by tboerger** [comment]
Closed in favor of #18, but thank you for your work!

**Pull request closed without merging**
